import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"
